listas = ['OBJETO', 1]
valores = [8, 2, 5, 4, 9, 3, 0]

#CRIA UMA LISTA
valores1 = list(range(4, 11))

#ADICIONAR OBJETOS
listas.append('OBJETO2') #PARA ADICIONAR UM OBJETO NA ULTIMA POSIÇAO
listas.insert(0, 'OBJETO3') #PARA ADICIONAR UM OBLETO NA POSIÇAO DETERMINADA(0)

#APAGAR OBJETOS
del listas[3] #DELETA O OBJETO DENTRO DA LISTA
listas.pop(3) #DELETA O OBJETO DESEJADO ## () VAZIOS FARA COM QUE O ULTIMO OBJETO SEJA DELETADO
listas.remove('OBJETO') #REMOVE O OBJETO PELO CONTEUDO "BATATA"

#ORGANIZAR OS OBJETOS EM ORDEM
valores.sort()
    #ORGANIZAR NA ORDEM REVERSA
valores.sort(reverse=True)

#CONTAGEM DE VALORES (OBJETO)
len(valores) #7

# OBS: LISTAS IGUAIS CRIAM UMA LIGAÇAO
a1 = [2, 3,  4, 7]
b1 = a1
    # PARA APENAS FAZER A COPIA E NAO INTERLIGA-LAS
b = a1[:]

#PARA LIMPAR A LISTA
listas.clear()

# FIM DA AULA