try:
    # O PROGRAMA VAI TENTAR REALIZAR ESSA OPERAÇÃO
except:
    # UM EXCEPT PODE SE REPETIR VARIAS VEZES DENTRO DE UM UNICO TRY:
    # except Exception as erro:  *PARA MOSTAR QUAL ERRO OCORREU
    # CASO O PROGRAMA DE ERRO
else:
    # CASO NÃO OCORRA ERRO NENHUM
    # OPÇÃO OPCIONAL
finally:
    # VAI EXECUTAR INDEPENDENTEMENTE SE OCORRA UM ERRO OU NÃO
